### ISSUE TITLE
Markers not revealing when cursor close

### ISSUE THREAD

**Issue by marzikill** [kjambunathan/org-extra-emphasis#6] opened 2022-10-05 21:45 UTC
Hey ! 

I really love what you've done with org-extra-emphasis. 
Is there a way i can show the marker used when the cursor comes close to the marked up text ? I would like the same behavior as there already is with *bold* etc when org-hide-emphasis-marker is set to t. 

![Screenshot_20221005_234152](https://user-images.githubusercontent.com/24573818/194169635-cf51e4e6-abb5-45e6-9512-a6aa11aa1bfd.png)
![Screenshot_20221005_234227](https://user-images.githubusercontent.com/24573818/194169646-f9b34969-8f5c-426a-8cc8-a000ebfd28ba.png)

**Comment by kjambunathan** [comment] 2022-10-07 05:56
This is a duplicate of [Integration with `org-appear`: Some markers don't hide](https://github.com/QiangF/org-extra-emphasis/issues/5). 

Auto hiding, revealing of markers is part of [`org-appear`: Make invisible parts of Org elements appear visible.](https://github.com/awth13/org-appear).  Does `spacemacs` or `doomemacs`, enable `org-appear-mode` by default.  

`org-appear` seems to be using `org-element` apis.  So, it would only understand `org` syntax.  The `extra emphasis markers` are NOT part of standard `org` syntax, so `org-appear` won't understand them.

I will take a look at what `org-appear` does, and see if there is a way to make `org-extra-emphasis` works with it.

This is not a bug, but a request for enhancement.


--------


There is some prior work on having `org-element` understand "custom" markers.  See https://emacs.stackexchange.com/a/12822/31220

The following snippet is a verbatim copy of the above Stackexchange response.


I have done something [similar](http://fredtantini.free.fr/blog/index.php?article13/un-peu-de-typographie-et-marquer-les-raccorcus-clavier-dans-org-mode). It\'s in French, but the code should speak for itself. I use `‰` for the marker (I use a [bepo](http://bepo.fr) layout), and when I do, the marked text as a pressed-button style.

I am not fluent in lisp, so there may be room for improvement.

What I have done is that, when using `‰` for marker, the marked text has a pressed-button style, and when exported it is translated to `<kbd>`

First, I had to define a new face:

```lisp
(defface my-face-org-keystroke
  '((t (:inherit shadow 
        :box (:line-width -2 ;neg. in order to keep the same size of lines
              :color "grey75"
              :style pressed-button)))) "Face for keystrokes"
        :group 'org-faces)
```

Then customize `org-emphasis-alist` :

```lisp
(("*" bold)
 ("/" italic)
 ("_" underline)
 ("=" org-code verbatim)
 ("~" org-verbatim verbatim)
 ("+"
  (:strike-through t))
 ("‰" my-face-org-keystroke verbatim));This line is what you want to add
```

For the export, you may need to load `ox.el` with `(require 'ox)`.

Then each time `bold` or `code` appears in a function (in `ox-org.el`), I have created a similar function (or modified existing ones):

```lisp
;creation
(defun org-html-keystroke (keystroke contents info)
  "Transcode KEYSTROKE from Org to HTML.
CONTENTS is nil.  INFO is a plist holding contextual
information."
  (format (or (cdr (assq 'my-object-keystroke org-html-text-markup-alist)) "%s")
          (org-html-encode-plain-text (org-element-property :value keystroke))))


;creation
(defun org-element-my-object-keystroke-parser ()
  "Parse code object at point.

Return a list whose CAR is `my-object-keystroke' and CDR is a plist with
`:value', `:begin', `:end' and `:post-blank' keywords.

Assume point is at the first tilde marker."
  (interactive)
  (save-excursion
    (unless (bolp) (backward-char 1))
    (looking-at org-emph-re)
    (let ((begin (match-beginning 2))
          (value (org-match-string-no-properties 4))
          (post-blank (progn (goto-char (match-end 2))
                             (skip-chars-forward " \t")))
          (end (point)))
      (list 'my-object-keystroke
            (list :value value
                  :begin begin
                  :end end
                  :post-blank post-blank)))))

;creation
(defun org-element-my-object-keystroke-interpreter (keystroke contents)
  "Interpret KEYSTROKE object as Org syntax.
CONTENTS is nil."
  (format "‰%s‰" (org-element-property :value keystroke)))


;modification
(defconst org-element-object-successor-alist
  '((subscript . sub/superscript) (superscript . sub/superscript)
    (bold . text-markup) (code . text-markup) (italic . text-markup)
    (strike-through . text-markup) (underline . text-markup)
    (verbatim . text-markup) (entity . latex-or-entity)
    (latex-fragment . latex-or-entity) (my-object-keystroke . text-markup))
  "Alist of translations between object type and successor name.
Sharing the same successor comes handy when, for example, the
regexp matching one object can also match the other object.")

;modification
(defconst org-element-all-objects
  '(bold code entity export-snippet footnote-reference inline-babel-call
         inline-src-block italic line-break latex-fragment link macro
         radio-target statistics-cookie strike-through subscript superscript
         table-cell target timestamp underline verbatim my-object-keystroke)
  "Complete list of object types.")


;modification
(defun org-element-text-markup-successor ()
  "Search for the next text-markup object.

Return value is a cons cell whose CAR is a symbol among `bold',
`italic', `underline', `strike-through', `code' and `verbatim'
and CDR is beginning position."
  (save-excursion
    (unless (bolp) (backward-char))
    (when (re-search-forward org-emph-re nil t)
      (let ((marker (match-string 3)))
        (cons (cond
               ((equal marker "*") 'bold)
               ((equal marker "/") 'italic)
               ((equal marker "_") 'underline)
               ((equal marker "+") 'strike-through)
               ((equal marker "~") 'code)
               ((equal marker "=") 'verbatim)
               ((equal marker "‰") 'my-object-keystroke) 
               (t (error "Unknown marker at %d" (match-beginning 3))))
              (match-beginning 2))))))
```

Next, I have defined a `my-html` backend for the export:

```lisp
(org-export-define-derived-backend 'my-html 'html
  :translate-alist '((my-object-keystroke . org-html-keystroke))
  :menu-entry ' (?h 1
                    ((?r "my-html"  org-html-export-to-my-html))))

(defun org-html-export-to-my-html
  (&optional async subtreep visible-only body-only ext-plist)
  "Export current buffer to a HTML file.

Return output file's name."
  (interactive)
  (let* ((extension (concat "." org-html-extension))
         (file (org-export-output-file-name extension subtreep))
         (org-export-coding-system org-html-coding-system))
    (org-export-to-file 'my-html file
      async subtreep visible-only body-only ext-plist)))


(defun org-html-publish-to-my-html (plist filename pub-dir)
  "Publish an org file to my-html.
Return output file name."
  (org-publish-org-to 'my-html filename
                      (concat "." (or (plist-get plist :html-extension)
                                      org-html-extension "html"))
                      plist pub-dir))

(defun org-html-convert-region-to-my-html ()
  "Assume the current region has org-mode syntax, and convert it to HTML.
This can be used in any buffer.  For example, you can write an
itemized list in org-mode syntax in an HTML buffer and use this
command to convert it."
  (interactive)
  (org-export-replace-region-by 'my-html))
```

So when I use `C-c C-e h r` it\'s exported correctly:

![enter image description here](https://i.stack.imgur.com/x6gbD.png)

![enter image description here](https://i.stack.imgur.com/qb2Q7.png)

![enter image description here](https://i.stack.imgur.com/UKUKm.png)

As suggested by OP in comments, you may need to use `org-mode-restart` (or `org-reload`) or kill/reload your buffer.

------------------------------------------------------------------------

**Edit:** This works for org-mode with versions prior 8.3 (that is till 8.2.10)

With versions ≥8.3.1, I have to modify

-   org-element-all-objects
-   possibly org-element-object-restrictions
-   org-element\--set-regexps
-   org-element\--object-lex

and of course still add the functions

-   org-element-my-object-keystroke-parser
-   org-element-my-object-keystroke-interpreter

but

-   org-element-object-successor-alist
-   org-element-text-markup-successor

are now deleted.

Thanks to [Charles C. Berry](http://permalink.gmane.org/gmane.emacs.orgmode/106232) for his help.

**Comment by kjambunathan** [comment] 2022-10-11 02:21
Accidentally closed because of a wrong issue number in a commit message.  Sorry.  This feature request will take to fix.  Reopening it.

**Closed as completed** 2024-12-07 03:13 UTC
